/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRiderRouteImport } from './routes/app.rider'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDriverRouteImport } from './routes/app.driver'
import { Route as AppRiderTripRouteImport } from './routes/app.rider.trip'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRiderRoute = AppRiderRouteImport.update({
  id: '/rider',
  path: '/rider',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDriverRoute = AppDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AppRoute,
} as any)
const AppRiderTripRoute = AppRiderTripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => AppRiderRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/driver': typeof AppDriverRoute
  '/app/history': typeof AppHistoryRoute
  '/app/rider': typeof AppRiderRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/rider/trip': typeof AppRiderTripRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/driver': typeof AppDriverRoute
  '/app/history': typeof AppHistoryRoute
  '/app/rider': typeof AppRiderRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/rider/trip': typeof AppRiderTripRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/driver': typeof AppDriverRoute
  '/app/history': typeof AppHistoryRoute
  '/app/rider': typeof AppRiderRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/rider/trip': typeof AppRiderTripRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/driver'
    | '/app/history'
    | '/app/rider'
    | '/app/'
    | '/app/rider/trip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/driver'
    | '/app/history'
    | '/app/rider'
    | '/app'
    | '/app/rider/trip'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/driver'
    | '/app/history'
    | '/app/rider'
    | '/app/'
    | '/app/rider/trip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rider': {
      id: '/app/rider'
      path: '/rider'
      fullPath: '/app/rider'
      preLoaderRoute: typeof AppRiderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/driver': {
      id: '/app/driver'
      path: '/driver'
      fullPath: '/app/driver'
      preLoaderRoute: typeof AppDriverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rider/trip': {
      id: '/app/rider/trip'
      path: '/trip'
      fullPath: '/app/rider/trip'
      preLoaderRoute: typeof AppRiderTripRouteImport
      parentRoute: typeof AppRiderRoute
    }
  }
}

interface AppRiderRouteChildren {
  AppRiderTripRoute: typeof AppRiderTripRoute
}

const AppRiderRouteChildren: AppRiderRouteChildren = {
  AppRiderTripRoute: AppRiderTripRoute,
}

const AppRiderRouteWithChildren = AppRiderRoute._addFileChildren(
  AppRiderRouteChildren,
)

interface AppRouteChildren {
  AppDriverRoute: typeof AppDriverRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRiderRoute: typeof AppRiderRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDriverRoute: AppDriverRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRiderRoute: AppRiderRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
